# CV is configerd using this TOML file. Things to know about TOML files:
# '#' is used as a comment character, any commented text will be processed as part of the config.
# Text must be surrounded by quotation marks to be processed (as a string).
# Arrays are declared using square brackets, and entries must be seperated by commas ','
# tables are declared using [name] (for eg. [config]). this is a single table that is declared once.
# nested tables are ones declared by [[name]], where each [[name]] entry is a sub-table in table. 

[config]
font_size=10 # 10, 11, 12 as per latex's document class sizes
font_scale=1 # multiplicative font spcale
page_margin=1.5
font="Calibri"

# order of the cv by each of the sections in this document, header is first.
cv_order=["header","skills","education","experience","projects"] 

# format of entry headers
education_header_order=["institution", "dates", "title", "location"]
experience_header_order=["institution","dates","title","location"]
project_header_order=["title, dates"]

#section titles. Must contain one per non header entry in cv_order.
section_titles=["Skills","Education","Experience","Projects, big"]

[header]
header_format=["email", "linkedin","github", "phone"]
name="Your Full Name"
name_size=14 #font size in pt.
location="Location, Earth"
phone="+123 1234 56789"
email="your-email@email.com"
linkedin="linkedin.com/your-linkedin"
github="github.com/your-github"

# skills are stored as key-value pairs, the key will be rendered as bold text, the value is the description.
[skills]
skill1 = "this is a great skill that I have."
skill2 = "so many skills."
LaTeX = "markup language."



[[education]]
title="Degree Title"
institution="University Name"
location="Location, Place"
dates="Sep 2022 - Jun 2027"
bulletpoints=[
	"Accomplishment 1",
	"Accomplishment 2",]

[[experience]]
title="Position 1"
institution="Company 1"
location="Place, Location"
dates="Nov 2023 - Present"
bulletpoints=[
			"Accomplishment 1.",
			"Accomplishment 2.",
			"Accomplishment 3.",
			]

[[experience]]
title="Position 2"
institution="Company 2"
location="Place, Locaiton"
dates="Nov 2023 - Present"
bulletpoints=[
			"Accomplishment 1 at 2nd company.",
			"Accomplishment 2 at 2nd company.",
			"Accomplishment 3 at 2nd company.",
			]


[[project]]
title="This Project"
description = "Has a short description."
dates="Present"
bulletpoints=[
	"Very cool project.",
	"Completely very well."	
	]

[[project]]
title="Another Project"
dates="Present"
bulletpoints=[
	"This project has no short description.",
]
